//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCC_GUI.Languages {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_cht {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_cht() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenCC_GUI.Languages.Language_cht", typeof(Language_cht).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 清空列表 的當地語系化字串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉換 的當地語系化字串。
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉換檔案 的當地語系化字串。
        /// </summary>
        internal static string ConvertFiles {
            get {
                return ResourceManager.GetString("ConvertFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉換文字 的當地語系化字串。
        /// </summary>
        internal static string ConvertText {
            get {
                return ResourceManager.GetString("ConvertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 複製 的當地語系化字串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 剪下 的當地語系化字串。
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯(&amp;E) 的當地語系化字串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 錯誤訊息 的當地語系化字串。
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 退出(&amp;x) 的當地語系化字串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案(&amp;F) 的當地語系化字串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔名 的當地語系化字串。
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 香港繁體到簡體 的當地語系化字串。
        /// </summary>
        internal static string hk2s {
            get {
                return ResourceManager.GetString("hk2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 語言 的當地語系化字串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載入(&amp;L)... 的當地語系化字串。
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 貼上 的當地語系化字串。
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簡體到香港繁體 的當地語系化字串。
        /// </summary>
        internal static string s2hk {
            get {
                return ResourceManager.GetString("s2hk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簡體到繁體 的當地語系化字串。
        /// </summary>
        internal static string s2t {
            get {
                return ResourceManager.GetString("s2t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簡體到臺灣正體 的當地語系化字串。
        /// </summary>
        internal static string s2tw {
            get {
                return ResourceManager.GetString("s2tw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簡體到臺灣正體（包括詞彙） 的當地語系化字串。
        /// </summary>
        internal static string s2twp {
            get {
                return ResourceManager.GetString("s2twp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉換並儲存(&amp;S)... 的當地語系化字串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全選(&amp;A) 的當地語系化字串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選取檔案... 的當地語系化字串。
        /// </summary>
        internal static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繁體到香港繁體 的當地語系化字串。
        /// </summary>
        internal static string t2hk {
            get {
                return ResourceManager.GetString("t2hk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繁體到簡體 的當地語系化字串。
        /// </summary>
        internal static string t2s {
            get {
                return ResourceManager.GetString("t2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繁體到臺灣正體 的當地語系化字串。
        /// </summary>
        internal static string t2tw {
            get {
                return ResourceManager.GetString("t2tw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 臺灣正體到簡體 的當地語系化字串。
        /// </summary>
        internal static string tw2s {
            get {
                return ResourceManager.GetString("tw2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 臺灣正體到簡體（包括詞彙） 的當地語系化字串。
        /// </summary>
        internal static string tw2sp {
            get {
                return ResourceManager.GetString("tw2sp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 撤銷 的當地語系化字串。
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
    }
}
